# Generated by Django 3.0.5 on 2020-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('W', 'Weapon'), ('C', 'Clothing'), ('F', 'Food'), ('S', 'Shoes'), ('B', 'Book'), ('T', 'Trinket')], default='W', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('starting_date', models.DateField(verbose_name='Starting Date')),
                ('occupation', models.CharField(choices=[('D', 'Doctor'), ('L', 'Lumberjack'), ('N', 'Ninja'), ('U', 'UPS Driver'), ('C', 'Card Dealer'), ('B', 'Boxer Bodybuilder')], default='D', max_length=1)),
                ('intellect', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('items', models.ManyToManyField(to='main_app.Item')),
            ],
        ),
    ]
