# Generated by Django 3.0.5 on 2020-04-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_character_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Item')),
                ('item_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ItemAction')),
                ('situation_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_reaction', to='main_app.Situation')),
                ('situation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_reactions', to='main_app.Situation')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Character')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Reaction')),
            ],
        ),
    ]
