# Generated by Django 3.0.5 on 2020-04-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_itemaction_log_reaction_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemaction',
            name='description',
        ),
    ]
