# Generated by Django 3.0.5 on 2020-04-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_itemaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='starting_date',
        ),
        migrations.AlterField(
            model_name='log',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main_app.Character'),
        ),
    ]
