# Generated by Django 3.0.5 on 2020-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_situation_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='response',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(choices=[('Run', 'Run'), ('Explore', 'Explore'), ('Fight', 'Fight'), ('Rest', 'Rest')], default='Run', max_length=20),
        ),
    ]
