# Generated by Django 3.0.5 on 2020-04-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200413_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='item_action',
        ),
    ]
